#!/bin/sh

EDITOR=${EDITOR:-nvim}

_select_by_tag() {
	TAG="$1"
	eval notmuch search tag:${TAG} | fzf | cut -d ' ' -f 1
}

### view: select a mail based on tags and display it in the configured editor.
view() {
	TAG=${1:-unread}
	THREAD="$($0 _select_by_tag ${TAG})"

	if [ -z "${THREAD}"]; then
		exit 1
	fi

	MAILFILE="$(mktemp)"
	notmuch show --format=mbox "${THREAD}" \
		> $MAILFILE

	eval "${EDITOR}" \
		\'+set filetype=mail\' \
		"${MAILFILE}"

	rm $MAILFILE
}

### alldone: marks all unread messages as read
alldone() {
	COUNT="$(notmuch count tag:unread)"

	notmuch tag -unread tag:unread \
		&& echo "Marked ${COUNT} messages as read."
}

### help: displays a help message listing all available commands
help() {
	grep "^### " "$0" \
		| sed 's/^### //' \
		| sed 's/: /|/' \
		| column -t -c 80 -s'|'
}

eval "$*" || help
